name: flutter_ex_kit
description: "Ex Kit Flutter is a powerful and easy-to-use collection of extensions and utility functions designed to enhance your Flutter development experience."
version: 0.0.4
repository: https://github.com/iamapuneet/flutter_ex_kit.git
issue_tracker: https://github.com/iamapuneet/flutter_ex_kit/issues
homepage: https://github.com/iamapuneet/flutter_ex_kit?tab=readme-ov-file#flutter_ex_kit
documentation: https://github.com/iamapuneet/flutter_ex_kit.wiki.git
topics: [flutter, extensions, utilities, development]
#funding: [https://github.com/sponsors/realpuneetsharam]

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The flutter ex kit package logo.
    path: screenshots/logo.png