name: flutter_ex_kit
description: "Ex Kit Flutter is a powerful and easy-to-use collection of extensions and utility functions designed to enhance your Flutter development experience."
version: 0.0.4
repository: https://github.com/realpuneetsharma/flutter_ex_kit.git
issue_tracker: https://github.com/realpuneetsharma/flutter_ex_kit/issues
homepage: https://realpuneetsharma.blogspot.com
documentation: https://realpuneetsharma.blogspot.com/blog-post_18
topics: [flutter, extensions, utilities, development]
funding: [https://github.com/sponsors/realpuneetsharam]
author: Puneet Sharma <developer.puneet.sharma@gmail.com>


environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The flutter ex kit package logo.
    path: screenshots/logo.png