name: "Dart"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION || 'stable' }}
          channel: "stable"

      - run: flutter doctor -v

      - run: flutter pub get

      - run: flutter test --coverage

      - run: npm install

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npx semantic-release

      - uses: codecov/codecov-action@v1.0.7
        with:
          tag: v0.0.${{ github.run_number }}
          release_name: Release ${{ github.ref }}
          token: ${{ secrets.TOKEN }}