name: "Dart & Flutter Flutter Ex Kit Plugin"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tar.gz archive
        run: |
          mkdir dist
          tar -czvf dist/flutter_ex_kit.tar.gz -C "${{ github.workspace }}" .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          makeLatest: true

          body: |
            🎉 **Flutter Ex Kit - Release v0.0.${{ github.run_number }}** 🎉

            🔥 **What's New**:
            - Implemented input validation for strings and integers.
            - Added string and integer extensions.
            - Improved media query handling for better responsiveness.
            - Enhanced documentation with better explanations and examples.

            📢 **Developed by:** Puneet Sharma  
            🆔 **GitHub Id:** [@iamapuneet](https://github.com/iamapuneet)  
            💼 **Project:** Flutter Ex Kit  

            👉 **Download the latest release below!**

      - name: Upload tar.gz to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/flutter_ex_kit.tar.gz
          asset_name: flutter_ex_kit.tar.gz
          asset_content_type: application/gzip
